config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'homes#top'
  get 'user/:id/follow' => 'users#follow', as: "user_follow"
  get 'user/:id/follower' => 'users#follower', as: "user_follower"
  resources :users do
    resource :relationships, only: [:create, :destroy]
  end
  resources :items do
    resource :favorites, only: [:create, :destroy]
    resources :item_comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :item_comments, dependent: :destroy

  attachment :item_image
end

app/models/item_comment.rb
class ItemComment < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  attachment :profile_image
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.name = 'ゲスト'
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def already_favorited?(item)
    self.favorites.exists?(item_id: item.id)
  end

  has_many :items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  has_many :item_comments, dependent: :destroy
  
  # ユーザーをフォローする、後ほどcontrollerで使用します。
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す、後ほどcontrollerで使用します。
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す、後ほどviewで使用します。
  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top]

  def after_sign_in_path_for(resource)
    items_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = current_user.favorites.new(item_id: params[:item_id])
    @favorite.save
    redirect_to request.referrer
  end

  def destroy
    @item = Item.find(params[:item_id])
    @favorite = current_user.favorites.find_by(item_id: @item.id)
    @favorite.destroy
    redirect_to request.referrer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all
  end
end

app/controllers/item_comments_controller.rb
class ItemCommentsController < ApplicationController
  def new
    @itemcomment = ItemComment.new
  end

  def create
    @item = Item.find(params[:item_id])
    @itemcomment = @item.item_comments.build(comment_params)
    if @itemcomment.save
      redirect_to items_path
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:item_comment).permit(:comment, :user_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @items = Item.all
    @item = current_user.items.new(item_params)
    if @item.save
      redirect_to items_path
    else
      render :new
    end
  end

  private

  def item_params
    params.require(:item).permit(:purchase_time, :name, :introduction, :item_url, :item_image_id)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to items_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @items = Item.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  def follow
    @user = User.find(params[:id])
    @follow = @user.following_user
  end

  def follower
    @user = User.find(params[:id])
    @follower = @user.follower_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/item_comments_helper.rb
module ItemCommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite.html.erb
<% if current_user.already_favorited?(item) %>
  <%= link_to item_favorites_path(item), method: :delete, remote: true do %>
    <i class="fas fa-heart text-danger"></i>
  <% end %>
<% else %>
  <%= link_to item_favorites_path(item), method: :post, remote: true do %>
    <i class="far fa-heart text-danger"></i>
  <% end %>
<% end %>
<%= item.favorites.count %>

app/views/homes/top.html.erb
<%= render 'shared/flash_messages' %>
<div class="mx-auto text-center">
  <h1 class="mt-5">BEST BUY COLLECTION</h1>
  <p>BEST BUY COLLECTIONはあなたの買って良かったものを投稿するアプリです。</p>
  <div class="mx-auto text-center">
    <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path,class: 'mt-5 btn btn-success', method: :post %>
  </div>
</div>
<div class="container">
  <div class="row no-gutters">
    <div class="col-12 col-sm-12 col-md-8 col-lg-6 col-xl-6 mx-auto text-center shadow-lg rounded px-0 my-5">
      <h4 class="text-dark bg-light p-4 mb-0"><strong>投稿一覧</strong></h4>
      <div class="form-body p-4 bg-light">
        <%= render 'items/index', items: @items %>
      </div>
    </div>
  </div>
</div>

app/views/item_comments/new.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-12 col-sm-12 col-md-8 col-lg-5 col-xl-5 mx-auto text-center shadow-lg rounded px-0 my-5">
      <h4 class="text-dark bg-light p-4 mb-0"><strong>コメントする</strong></h4>
      <div class="form-body p-4 bg-light">
        <%= form_with model:@itemcomment, url: item_item_comments_path, local:true do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="input-group mb-3">
          <%= f.text_area :comment, size: "1x4", class:"form-control", placeholder:"商品コメント" %>
        </div>
          <%= f.submit "投稿する", class:"btn btn-block btn-success mt-5" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/_index.html.erb
<% @items.each do |item| %>
  <div class="card mt-3">
    <div class="container">
      <div class="row no-gutters">
        <div class="col-4 mt-3">
          <%= link_to user_path(item.user), :style=>"color:black;" do %>
            <div>
              <%= attachment_image_tag(item.user, :profile_image, size: "50x50", fallback: "no_image.png") %>
            </div>
            <div class="mt-3">
              <%= item.user.name %>
            </div>
          <% end %>
        </div>
        <div class="col-8 mt-3">
          <%= link_to item_path(item), :style=>"color:black;" do %>
            <div>
              <%= attachment_image_tag(item, :item_image, size: "200x200", fallback: "no_image.png") %>
            </div>
            <div  class="mt-3">
              <%= item.purchase_time.strftime("%-m月") %>
              <%= item.name %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="container mt-3 mb-3">
      <div class="row no-gutters">
        <div class="col-8">
        </div>
        <% if user_signed_in? %>
        <div class="col-2">
          <%= render partial: 'favorites/favorite', locals: { item: item} %>
        </div>
        <% else %>
        <% end %>
        <div class="col-2">
          <%= link_to new_item_item_comment_path(item) do %>
            <i class="far fa-comment text-dark"></i>
          <% end %>
          <%= item.item_comments.count %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/items/index.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-12 col-sm-12 col-md-8 col-lg-6 col-xl-6 mx-auto text-center shadow-lg rounded px-0 my-5">
      <h4 class="text-light bg-info p-4 mb-0"><strong>投稿一覧</strong></h4>
      <div class="form-body p-4 bg-light">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-block btn-success" data-toggle="modal" data-target="#exampleModal">投稿する</button>
        <div class="items">
          <%= render 'index', items: @items %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel"><strong>投稿画面</strong></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with model:@item, url: items_path, local:true do |f| %>
        <div class="modal-body">
          <div class="input-group mb-3 mt-4">
            <%= f.date_select :purchase_time, {:discard_day => true, :discard_year => true} %>
          </div>
          <div class="input-group mb-3 mt-4">
            <%= f.attachment_field :item_image, placeholder: "商品画像" %>
          </div>
          <div class="input-group mb-3 mt-4">
            <%= f.text_field :name, size: "1x3", class:"form-control", placeholder:"商品名" %>
          </div>
          <div class="input-group mb-3 mt-4">
            <%= f.text_area :introduction, size: "1x3", class:"form-control", placeholder:"商品説明" %>
          </div>
          <div class="input-group mb-3 mt-4">
            <%= f.text_area :item_url, size: "1x3", class:"form-control", placeholder:"商品URL" %>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.submit "投稿する", class:"btn btn-block btn-success mt-5" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-12 col-sm-12 col-md-8 col-lg-6 col-xl-6 mx-auto text-center shadow-lg rounded px-0 my-5">
      <h4 class="text-dark bg-light p-4 mb-0"><strong>投稿詳細</strong></h4>
      <div class="form-body p-4 bg-light">
        <div>
          <h5><strong><%= @item.purchase_time.strftime("%-m月") %>に買って良かった物</strong></h5>
        </div>
        <div class="mt-3">
          <%= attachment_image_tag(@item, :item_image, size: "300x300", fallback: "no_image.png") %>
        </div>
        <div class="mt-3">
          <%= @item.name %>
        </div>
        <div class="mt-3">
          <%= @item.introduction %>
        </div>
        <div class="mt-3">
          <%= Rinku.auto_link(@item.item_url, :all, 'target="_blank"').html_safe %>
        </div>
        <div class="container mt-3">
          <div class="row no-gutters">
            <div class="col-8">
            </div>
            <div class="col-2">
              <%= render partial: 'favorites/favorite', locals: { item: @item} %>
            </div>
            <div class="col-2">
              <%= link_to new_item_item_comment_path(@item) do %>
                <i class="far fa-comment text-dark"></i>
              <% end %>
              <%= @item.item_comments.count %>
            </div>
          </div>
        </div>
        <div>
          <% @item.item_comments.each do |item_comment| %>
            <p><%= item_comment.comment %></p>
            <hr>
          <% end %>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/users/follow.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 mx-auto text-center shadow-lg px-0 my-5">
      <h4 class="text-light bg-info py-4 mb-0"><strong><%= @user.name %>さんのフォロ一覧</strong></h4>
      <div class="p-4 bg-light">
        <% @follow.each do |user| %>
          <%= link_to user, class: "user_#{user.id}", :style=>"color:black;" do %>
          <div class="container">
            <div class="row no-gutters">
              <div class="col-4">
                <div>
                    <%= attachment_image_tag(user, :profile_image, size: "50x50", fallback: "no_image.png") %>
                </div>
                </div>
                <div class="col-8">
                  <p><%= user.name %></p>
                  <p><%= user.introduction %></p>
                </div>
              </div>
            </div>
          <hr>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/follower.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 mx-auto text-center shadow-lg px-0 my-5">
      <h4 class="text-light bg-info py-4 mb-0"><strong><%= @user.name %>さんのフォロワー一覧</strong></h4>
      <div class="p-4 bg-light">
        <% @follower.each do |user| %>
          <%= link_to user, class: "user_#{user.id}", :style=>"color:black;" do %>
            <div class="container">
              <div class="row no-gutters">
               <div class="col-4">
                  <div>
                    <%= attachment_image_tag(user, :profile_image, size: "50x50", fallback: "no_image.png") %>
                  </div>
                </div>
                <div class="col-8">
                  <p><%= user.name %></p>
                  <p><%= user.introduction %></p>
                </div>
              </div>
            </div>
            <hr>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 mx-auto text-center shadow-lg px-0 my-5">
      <h4 class="text-light bg-info py-4 mb-0"><strong><%= @user.name %>さんのプロフィール</strong></h4>
      <div class="p-4 bg-light">
        <div>
          <%= attachment_image_tag(@user, :profile_image, size: "100x100", fallback: "no_image.png") %>
        </div>
        <div class="mt-3">
          <%= @user.name %>
        </div>
        <div class="mt-3">
          <%= @user.introduction %>
        </div>
        <div class="mt-3">
          <%= link_to user_follow_path(@user.id), :style=>"color:black;" do %>
            <%= "#{@user.follower.count} フォロー" %>
          <% end %>
          <%= link_to user_follower_path(@user.id), :style=>"color:black;" do %>
          <%= "#{@user.followed.count} フォロワー" %>
          <% end %>
        </div>
        <div class="mt-3">
          <% if @user.id != current_user.id %>
            <% if current_user.following?(@user) %>
              <%= link_to 'フォロー外す', user_relationships_path(@user.id), class:"btn btn-danger", method: :delete %>
            <% else %>
              <%= link_to 'フォローする', user_relationships_path(@user.id), class:"btn btn-info", method: :POST %>
            <% end %>
          <% end %>
        </div>
        <% if @user.id == current_user.id %>
          <!-- Button trigger modal -->
          <button type="button" class="btn btn-block btn-success mt-3" data-toggle="modal" data-target="#exampleModal">編集する</button>
        <% end %>
        <hr>
        <h5 class="text-dark bg-light py-4 mb-0"><strong><%= @user.name %>さんの投稿一覧</strong></h5>
        <% @items.each do |item| %>
          <div class="mt-3">
            <% if item.user_id == current_user.id %>
              <div class="container card">
                <div class="row no-gutters">
                  <div class="col-4 mt-3 mb-3">
                    <div>
                      <%= attachment_image_tag(item.user, :profile_image, size: "50x50", fallback: "no_image.png") %>
                    </div>
                    <div class="mt-3">
                      <%= item.user.name %>
                    </div>
                  </div>
                  <div class="col-8 mt-3 mb-3">
                    <%= link_to item_path(item), :style=>"color:black;" do %>
                      <div>
                        <%= attachment_image_tag(item, :item_image, size: "200x200", fallback: "no_image.png") %>
                      </div>
                      <div  class="mt-3">
                        <%= item.purchase_time.strftime("%-m月") %>
                        <%= item.name %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel"><strong>プロフィール編集</strong></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with model: @user, url: user_path, remote: true do |f| %>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-user"></i></span>
            </div>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-user"></i></span>
            </div>
            <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputName", placeholder:"名前"%>
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-user"></i></span>
            </div>
            <%= f.text_area :introduction, autofocus: true, class:"form-control", id:"inputIntroduction", placeholder:"自己紹介"%>
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-envelope"></i></span>
            </div>
            <%= f.email_field :email, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"メールアドレス" %>
          </div>
          </div>
          <div class="modal-footer">
          <%= f.submit "変更内容保存", class:"btn btn-block btn-success mt-5" %>
          </div>
        <% end %>
    </div>
  </div>
</div>